### ISSUE TITLE
Vaadin Version Too Old

### ISSUE THREAD

**Issue by purplecaesar** [maxschuster/Vaadin-SignatureField#5]
In your POM.xml

```
......
 <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <vaadin.version>7.4.0</vaadin.version>
        <vaadin.plugin.version>${vaadin.version}</vaadin.plugin.version>
.......
```

When I use Vaadin 7.6.1, the widgetset compile will cause some error.

**Comment by maxschuster** [comment]
This add-on should have no influence on your widgetset, because it does not contain any widgets or widgetsets.

Could you add some additional information, please? Like the widgetset compile log.

The version 7.4.0 is the min api version required by the add-on. I'm using it with Vaadin 7.6.4 without any problems.

**Comment by purplecaesar** [comment]
As I replied in mail. I use Vaadin-On-Grails, and add the dependency in the Grails configuration. Which will cause the Grails download the Vaadin 7.4.0 via the pom.xml of the add-on. So if anyone want to use Vaadin-On-Grails, please download the source code and recompile it. It works any really good!

**Comment by maxschuster** [comment]
I'm glad that you were able to solve this problem on your own. I've never used Grails, but it sounds strange to me that you can't define the version of vaadin that you want to use.
